name = "airbus"
main = "server/index.ts"
compatibility_date = "2026-08-04"
workers_dev = false

[assets]
not_found_handling = "single-page-application"

[vars]
ASSETS_BASE_URL = "https://assets.medowo.net"
DIRECT_DOMAINS = "medowo.net"

[triggers]
crons = [ '0 0 * * *' ]

[[d1_databases]]
binding = "DB"
database_name = "airbus"
database_id = "2a28bd4b-f320-4f81-91ab-3cca39c562fc"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = false
